version: '3'

networks:
  mvc-interfaces:

services:
  php:
    image: jorge07/alpine-php:${PHP_VERSION}-dev
    container_name: mvc-interfaces-php
    volumes:
      - ../:/var/www/html
    ports:
      - "${PHP_PORT}:9000"
      - "${SSH_PORT}:22"
    working_dir: /var/www/html
    networks:
      - mvc-interfaces