version: '3'

networks:
  mvc-interfaces:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.4.0/24
          gateway: 10.10.4.1

services:
  php:
    build: php
    container_name: 'mvc-interfaces-php'
    volumes:
      - ../:/var/www/html
    ports:
      - "9000:9000"
    working_dir: /var/www/html
    networks:
      mvc-interfaces:
        ipv4_address: 10.10.4.2
